name: shophub
description: "Application e-commerce multivendeur construite avec Flutter et Riverpod."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  shared_preferences: ^2.2.3
  dio: ^5.7.0
  flutter_secure_storage: ^9.2.2
  hive_flutter: ^1.1.0
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.8
  image_picker: ^1.2.3
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
